language: python
python:
  - "2.6"
  - "2.7"
install:
  - pip install -r requirements.txt
  - git clone https://gitorious.org/pygnutls/pygnutls.git && cd pygnutls && python setup.py install && cd ..
  - python setup.py install
script:
  - nosetests tests
